### ISSUE TITLE
Value not valid

### ISSUE THREAD

**Issue by DaVinciLord** [Alsatian67/FormBundle#7]
Hi,
When I try to add a non existing value (for example, a non existing country entity in database), Symfony fire a "This value is not valid" error.
The new value when submitting the form is just a string and I'd like to convert it to a new Country entity.
How can I proceed using this bundle ?

**Comment by Alsatian67** [comment]
It can only work if the string you send represents an entity from your country table.
I can also not change the bundle for that, since the entity type is designed to verify the entity existence.

If you want to allow free strings, you can use the extensible_choice type instead of extensible_entity, and create your new entity with your own logic.

**Comment by DaVinciLord** [comment]
I did that, thanks for your help.
